                                          
extern unsigned char xdata OUTPORT1_ADD	 ;
extern unsigned char xdata OUTPORT2_ADD  ;
extern unsigned char xdata ADC_ADD    	 ;
//public unsigned char xdata DUART_ADD   ;
//public unsigned char xdata LCD_ADD     ;
//extern unsigned char xdata PHASE_ADD     ;
//extern unsigned char xdata DTMF_TXRX_ADD ;
extern unsigned char xdata INPORT1_ADD   ;
extern unsigned char xdata INPORT2_ADD   ;
extern unsigned char xdata INPORT3_ADD   ;
extern unsigned char xdata INPORT4_ADD   ;
extern unsigned char xdata INPORT5_ADD   ;
extern unsigned char xdata INPORT6_ADD   ;
extern unsigned char xdata INPORT7_ADD   ;
extern unsigned char xdata INPORT8_ADD   ;
extern unsigned char xdata NVRAM_START_ADDR	;
extern unsigned char xdata NVRAM_END_ADDR	;
extern unsigned char xdata  DUART_MRA_WRITE_ADDR;
extern unsigned char xdata  DUART_CSRA_ADDR	;
extern unsigned char xdata  DUART_CRA_ADDR	;
extern unsigned char xdata  DUART_THRA_ADDR	;
extern unsigned char xdata  DUART_ACR_ADDR	;
extern unsigned char xdata  DUART_IMR_ADDR	;
extern unsigned char xdata  DUART_CTU_WRITE_ADDR;
extern unsigned char xdata  DUART_CTL_WRITE_ADDR;
extern unsigned char xdata  DUART_MRB_WRITE_ADDR;
extern unsigned char xdata  DUART_CSRB_ADDR	;
extern unsigned char xdata  DUART_CRB_ADDR	;
extern unsigned char xdata  DUART_THRB_ADDR	;
extern unsigned char xdata  DUART_IVR_WRITE_ADDR;
extern unsigned char xdata  DUART_OPCR_ADDR   	;
extern unsigned char xdata  DUART_SOPBC_ADDR 	;
extern unsigned char xdata  DUART_COPBC_ADDR 	;
extern unsigned char xdata  LCD_CMD_ADDR	;
extern unsigned char xdata  LCD_DATA_ADDR 	;
//added in Ver1.2
extern unsigned char xdata DTMF_CNTL_ADDR   ;
extern unsigned char xdata DTMF_STAT_ADDR 	;
extern unsigned char xdata DTMF_TX_ADDR	    ;
extern unsigned char xdata DTMF_RX_ADDR 	;
extern unsigned char xdata DTMF_TX_ID 	;//***********************/
extern unsigned char xdata DTMF_RX_ID 	;//**********************/
//ends here

