
public void GetPsuVoltages(void);
public void GetCh1AgcVoltage (void);
public void GetCh2AgcVoltage(void);
public void ConvertHexToAscii(unsigned char * HexStr, unsigned char HexCount,unsigned char * AsciiStr );
public void ConvertAsciiToHex(unsigned char * AsciiStr, unsigned char AsciiCount, unsigned char * HexStr );
public unsigned char KeyBoardScan(void);
public void StringOut(unsigned char *DisplayStr, unsigned char Row, unsigned int Col);
public unsigned char SelectionCursorPosition(unsigned char Row, unsigned char Column);

