/*###########################################################################
Project				:	PLCC Supy
Filename				:	SpFunReg.H
Previous Version	:  N/A
New Version			:	0.1
Modified  on		:      13-04-1999
Last Modified by	:	G.S.Ubhi
Editor Tab Size  	:	3
Comments				:
############################################################################*/
sbit P1_0 = P1^0;
sbit P1_1 = P1^1;
sbit P1_2 = P1^2;
sbit P1_3 = P1^3;
sbit Ch_sel = P1^4;
sbit P1_5 = P1^5;
sbit P1_6 = P1^6;
sbit DTMF_en = P1^7;

/*###################### End Of File " SpFunReg.h " #######################*/

